name: 打包
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 检查提交消息
        id: check_message
        shell: bash
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ^[0-9]{2}$ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
          else
            echo "match=false" >> $GITHUB_OUTPUT
          fi

      - name: 执行打包
        if: steps.check_message.outputs.match == 'true'
        run: |
          echo "检查版本号通过，开始打包..."